# Generated by Django 3.1.4 on 2021-05-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20210523_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresults',
            options={'verbose_name_plural': 'search'},
        ),
    ]
