# Generated by Django 3.1.4 on 2021-05-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20210523_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresults',
            options={'verbose_name_plural': 'add links'},
        ),
    ]
