# Generated by Django 3.1.4 on 2021-05-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20210523_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresults',
            options={'verbose_name_plural': 'link'},
        ),
        migrations.RenameField(
            model_name='searchresults',
            old_name='link',
            new_name='name',
        ),
    ]
