# Generated by Django 3.1.4 on 2021-05-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20210523_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresults',
            old_name='discription',
            new_name='description',
        ),
    ]
